//go:build darwin && !cgo

package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	desktopAppName       = "Codextra"
	desktopAppExecutable = "codextra-desktop"
)

// installDesktopApp generates ~/Applications/Codextra.app — a clickable launcher
// that runs `codextra --desktop`, so Codex Desktop opens behind the codextra
// proxy without touching the CLI. The bundle uses the codextra logo as its icon.
func installDesktopApp() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("find codextra executable: %w", err)
	}
	if resolved, rerr := filepath.EvalSymlinks(exe); rerr == nil {
		exe = resolved
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	appsDir := filepath.Join(home, "Applications")
	if err := os.MkdirAll(appsDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", appsDir, err)
	}
	appPath := filepath.Join(appsDir, desktopAppName+".app")

	if err := writeDesktopAppBundle(appPath, exe, resolveCodexBin()); err != nil {
		return err
	}
	// Bump the bundle mtime so Launch Services refreshes the icon.
	_ = exec.Command("touch", appPath).Run()

	fmt.Printf("Installed %s\n", appPath)
	fmt.Println("Open it from Finder, Launchpad, or the Dock to launch Codex Desktop behind the codextra proxy.")
	fmt.Printf("Remove it with: rm -rf %q\n", appPath)
	return nil
}

func writeDesktopAppBundle(appPath, codextraExe, codexBin string) error {
	contents := filepath.Join(appPath, "Contents")
	macOSDir := filepath.Join(contents, "MacOS")
	resDir := filepath.Join(contents, "Resources")
	for _, d := range []string{macOSDir, resDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}

	if err := os.WriteFile(filepath.Join(contents, "Info.plist"), []byte(desktopAppInfoPlist), 0o644); err != nil {
		return fmt.Errorf("write Info.plist: %w", err)
	}

	launcher := filepath.Join(macOSDir, desktopAppExecutable)
	if err := os.WriteFile(launcher, []byte(desktopLauncherScript(codextraExe, codexBin)), 0o755); err != nil {
		return fmt.Errorf("write launcher: %w", err)
	}

	// A generic icon is acceptable if rendering fails, so this is best-effort.
	if err := writeDesktopAppIcon(filepath.Join(resDir, "codextra.icns")); err != nil {
		log.Printf("codextra: app icon unavailable, using the system default: %v", err)
	}
	return nil
}

// resolveCodexBin locates the codex binary at install time and bakes it into the
// launcher, because macOS launches apps with a minimal PATH that won't include
// Homebrew or ~/.local/bin. Returns "" if codex can't be found now; the launcher
// then falls back to PATH at run time.
func resolveCodexBin() string {
	if v := os.Getenv("CODEXTRA_CODEX_BIN"); v != "" {
		return v
	}
	if p, err := exec.LookPath("codex"); err == nil {
		return p
	}
	return ""
}

func desktopLauncherScript(codextraExe, codexBin string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by `codextra install-app` — launches Codex Desktop behind the codextra proxy.\n")
	b.WriteString(`export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/bin:$PATH"` + "\n")
	if codexBin != "" {
		b.WriteString("export CODEXTRA_CODEX_BIN=" + shellSingleQuote(codexBin) + "\n")
	}
	b.WriteString("exec " + shellSingleQuote(codextraExe) + " --desktop\n")
	return b.String()
}

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const desktopAppInfoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key><string>Codextra</string>
	<key>CFBundleDisplayName</key><string>Codextra</string>
	<key>CFBundleIdentifier</key><string>com.gabewillen.codextra.desktop</string>
	<key>CFBundleExecutable</key><string>codextra-desktop</string>
	<key>CFBundleIconFile</key><string>codextra</string>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
	<key>CFBundleVersion</key><string>1</string>
	<key>CFBundleShortVersionString</key><string>1.0</string>
	<key>LSMinimumSystemVersion</key><string>11.0</string>
	<key>LSUIElement</key><true/>
</dict>
</plist>
`

// writeDesktopAppIcon renders the codextra logo into a .icns using macOS's own
// iconutil over a generated .iconset of the standard sizes.
func writeDesktopAppIcon(icnsPath string) error {
	tmp, err := os.MkdirTemp("", "codextra-iconset-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	iconset := filepath.Join(tmp, "codextra.iconset")
	if err := os.MkdirAll(iconset, 0o755); err != nil {
		return err
	}

	// Render one anti-aliased 1024 master, then box-downsample it (by integer
	// factors, since 1024 divides each target) to every iconset size — far
	// cheaper than re-rendering each size at high supersample.
	master, err := renderAppIcon(1024)
	if err != nil {
		return err
	}
	for _, e := range []struct {
		name string
		px   int
	}{
		{"icon_16x16.png", 16}, {"icon_16x16@2x.png", 32},
		{"icon_32x32.png", 32}, {"icon_32x32@2x.png", 64},
		{"icon_128x128.png", 128}, {"icon_128x128@2x.png", 256},
		{"icon_256x256.png", 256}, {"icon_256x256@2x.png", 512},
		{"icon_512x512.png", 512}, {"icon_512x512@2x.png", 1024},
	} {
		img := master
		if e.px != 1024 {
			img = downsample(master, 1024/e.px)
		}
		var buf bytes.Buffer
		if err := png.Encode(&buf, img); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(iconset, e.name), buf.Bytes(), 0o644); err != nil {
			return err
		}
	}

	if out, err := exec.Command("iconutil", "-c", "icns", iconset, "-o", icnsPath).CombinedOutput(); err != nil {
		return fmt.Errorf("iconutil: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// appIconPNG renders the app icon at the given size and returns it as PNG bytes.
func appIconPNG(size int) ([]byte, error) {
	img, err := renderAppIcon(size)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderAppIcon draws the logo (black) centered on a white rounded-square tile at
// the given size, supersampled 2x for smooth edges.
func renderAppIcon(size int) (*image.RGBA, error) {
	logoPaths, err := loadLogoSVGPaths()
	if err != nil {
		return nil, err
	}

	const ss = 2
	big := size * ss
	canvas := image.NewRGBA(image.Rect(0, 0, big, big))

	fillRoundedRect(canvas, big, float64(big)*0.22, color.RGBA{R: 0xff, G: 0xff, B: 0xff, A: 0xff})

	const viewBox = 20.0
	const logoFrac = 0.6
	scale := float64(big) * logoFrac / viewBox
	offset := (float64(big) - viewBox*scale) / 2

	var contours []pathContour
	for idx, raw := range logoPaths {
		pc, perr := parsePathContours(raw, func(x, y float64) point {
			return point{x: offset + x*scale, y: offset + y*scale}
		})
		if perr != nil {
			return nil, fmt.Errorf("svg path %d: %w", idx, perr)
		}
		contours = append(contours, pc...)
	}
	fillContours(canvas, contours, color.RGBA{A: 0xff})

	return downsample(canvas, ss), nil
}

// fillRoundedRect fills a rounded square of the given side and corner radius.
func fillRoundedRect(img *image.RGBA, side int, radius float64, c color.RGBA) {
	max := float64(side)
	for y := 0; y < side; y++ {
		for x := 0; x < side; x++ {
			fx, fy := float64(x)+0.5, float64(y)+0.5
			var dx, dy float64
			switch {
			case fx < radius:
				dx = radius - fx
			case fx > max-radius:
				dx = fx - (max - radius)
			}
			switch {
			case fy < radius:
				dy = radius - fy
			case fy > max-radius:
				dy = fy - (max - radius)
			}
			if dx*dx+dy*dy <= radius*radius {
				img.SetRGBA(x, y, c)
			}
		}
	}
}

// downsample box-filters img by factor, premultiplied-correct so the transparent
// rounded corners don't leave a gray fringe.
func downsample(src *image.RGBA, factor int) *image.RGBA {
	w := src.Bounds().Dx() / factor
	h := src.Bounds().Dy() / factor
	dst := image.NewRGBA(image.Rect(0, 0, w, h))
	n := factor * factor
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			var pr, pg, pb, pa int
			for dy := 0; dy < factor; dy++ {
				for dx := 0; dx < factor; dx++ {
					c := src.RGBAAt(x*factor+dx, y*factor+dy)
					a := int(c.A)
					pr += int(c.R) * a / 255
					pg += int(c.G) * a / 255
					pb += int(c.B) * a / 255
					pa += a
				}
			}
			avgA := pa / n
			var rr, gg, bb int
			if avgA > 0 {
				rr = clamp255(pr / n * 255 / avgA)
				gg = clamp255(pg / n * 255 / avgA)
				bb = clamp255(pb / n * 255 / avgA)
			}
			dst.SetRGBA(x, y, color.RGBA{R: uint8(rr), G: uint8(gg), B: uint8(bb), A: uint8(avgA)})
		}
	}
	return dst
}

func clamp255(v int) int {
	switch {
	case v > 255:
		return 255
	case v < 0:
		return 0
	default:
		return v
	}
}
